<script setup>
import { ref } from 'vue'
import { useCartStore } from '../stores/cart'
import { useLanguageStore } from '../stores/language'
import EmptyState from '../components/common/EmptyState.vue'
import AppImage from '../components/common/AppImage.vue'
import CheckoutDialog from '../components/common/CheckoutDialog.vue'
import { productTitle } from '../data/translations'
const cart = useCartStore(), language = useLanguageStore()
const checkoutVisible = ref(false)
</script>
<template><section class="container page cart-page"><div class="page-intro"><span class="eyebrow">{{ language.t('yourSelection') }}</span><h1>{{ language.t('cart') }}</h1></div><EmptyState v-if="!cart.items.length" icon="🛒" :title="language.t('emptyCart')" :action="language.t('continueShopping')" /><div v-else class="cart-layout"><div class="cart-list"><article v-for="item in cart.items" :key="item.product.id" class="cart-item"><RouterLink :to="`/product/${item.product.id}`"><AppImage :src="item.product.image" :alt="productTitle(item.product, language.locale)" /></RouterLink><div class="cart-item-copy"><RouterLink :to="`/product/${item.product.id}`">{{ productTitle(item.product, language.locale) }}</RouterLink><p>{{ item.product.seller }}</p><strong>{{ language.price(item.product.price) }}</strong><div class="quantity-control"><button aria-label="decrease" @click="cart.setQuantity(item.product.id,item.quantity-1)">−</button><span>{{ item.quantity }}</span><button aria-label="increase" @click="cart.setQuantity(item.product.id,item.quantity+1)">+</button></div><button class="text-button" @click="cart.remove(item.product.id)">{{ language.t('remove') }}</button></div><strong class="cart-line-price">{{ language.price(item.product.price * item.quantity) }}</strong></article></div><aside class="order-summary"><h2>{{ language.t('total') }}</h2><div><span>{{ language.t('subtotal') }}</span><b>{{ language.price(cart.subtotal) }}</b></div><div><span>{{ language.t('shipping') }}</span><b>{{ cart.subtotal >= 299 ? language.price(0) : language.price(18) }}</b></div><div class="grand-total"><span>{{ language.t('total') }}</span><strong>{{ language.price(cart.subtotal + (cart.subtotal >= 299 ? 0 : 18)) }}</strong></div><button class="button primary wide" @click="checkoutVisible = true">{{ language.t('checkout') }}</button><button class="text-button" @click="cart.clear">{{ language.t('clearCart') }}</button></aside></div><CheckoutDialog v-model:visible="checkoutVisible" /></section></template>
