<script setup>
import { computed } from 'vue'
import { products } from '../data/products'
import { categories } from '../data/categories'
import { useLanguageStore } from '../stores/language'
import ProductGrid from '../components/product/ProductGrid.vue'
import CategoryCard from '../components/category/CategoryCard.vue'
const language = useLanguageStore(); const popular = computed(() => products.slice(0,5)); const trending = computed(() => products.slice(5,10)); const newProducts = computed(() => products.slice(10,15)); const offers = computed(() => products.slice(15,20));
</script>
<template><div class="home-page"><section class="hero container"><div class="hero-copy"><span class="eyebrow">{{ language.t('heroEyebrow') }}</span><h1>{{ language.t('heroTitle') }}</h1><p>{{ language.t('heroText') }}</p><RouterLink class="button primary" to="/products">{{ language.t('explore') }} <span>→</span></RouterLink></div><img src="/assets/images/banners/craft-hero.svg" alt="Handcrafted pottery and flowers" fetchpriority="high" /></section><section class="container section"><div class="section-heading"><h2>{{ language.t('trending') }}</h2><RouterLink to="/products">{{ language.t('viewAll') }} →</RouterLink></div><ProductGrid :products="trending" /></section><section class="container section"><div class="section-heading"><h2>{{ language.t('newArrivals') }}</h2><RouterLink to="/products">{{ language.t('viewAll') }} →</RouterLink></div><ProductGrid :products="newProducts" /></section><section class="container section"><div class="section-heading"><div><span class="eyebrow">{{ language.t('details') }}</span><h2>{{ language.t('categories') }}</h2></div><RouterLink to="/products">{{ language.t('viewAll') }} →</RouterLink></div><div class="category-grid"><CategoryCard v-for="category in categories.slice(1)" :key="category.id" :category="category" /></div></section><section class="feature-banner container"><img src="/assets/images/banners/studio-hero.svg" alt="Craft studio" /><div><span class="eyebrow">{{ language.t('featureEyebrow') }}</span><h2>{{ language.t('featureTitle') }}</h2><p>{{ language.t('featureText') }}</p><RouterLink to="/category/art" class="text-link">{{ language.t('explore') }} →</RouterLink></div></section><section class="container section"><div class="section-heading"><h2>{{ language.t('popular') }}</h2><RouterLink to="/products">{{ language.t('viewAll') }} →</RouterLink></div><ProductGrid :products="popular" /></section><section class="container section last-section"><div class="section-heading"><h2>{{ language.t('specialOffers') }}</h2><RouterLink to="/products">{{ language.t('viewAll') }} →</RouterLink></div><ProductGrid :products="offers" /></section></div></template>
