<script setup>
import { computed, ref } from 'vue'
import { useRoute } from 'vue-router'
import { products } from '../data/products'
import { useLanguageStore } from '../stores/language'
import { useCartStore } from '../stores/cart'
import { productBadge, productTitle, productDescription } from '../data/translations'
import ProductGallery from '../components/product/ProductGallery.vue'
import ProductGrid from '../components/product/ProductGrid.vue'
import FavoriteButton from '../components/product/FavoriteButton.vue'
import EmptyState from '../components/common/EmptyState.vue'
const route = useRoute(), language = useLanguageStore(), cart = useCartStore(); const product = computed(() => products.find(p => p.id === Number(route.params.id))); const quantity = ref(1); const added = ref(false); const activeTab = ref('description')
const add = () => { cart.add(product.value, quantity.value); added.value = true; setTimeout(() => added.value = false, 1500) }; const related = computed(() => product.value ? products.filter(p => p.category === product.value.category && p.id !== product.value.id).slice(0,4) : []); const title = computed(() => product.value && productTitle(product.value, language.locale)); const description = computed(() => product.value && productDescription(product.value, language.locale)); const badge = computed(() => product.value && productBadge(product.value.badge, language.locale))
</script>
<template><section v-if="product" class="container page detail-page"><div class="breadcrumbs"><RouterLink to="/products">{{ language.t('products') }}</RouterLink><span>/</span><RouterLink :to="`/category/${product.category}`">{{ language.category(product.category) }}</RouterLink></div><div class="detail-layout"><ProductGallery :product="product" /><div class="detail-info"><span class="eyebrow">{{ badge || language.t('handmade') }}</span><h1>{{ title }}</h1><p class="detail-seller">{{ language.t('seller') }} · {{ product.seller }}</p><div class="detail-rating">★ {{ product.rating }} <u>{{ product.reviewCount }} {{ language.t('reviews') }}</u></div><div class="detail-price"><strong>{{ language.price(product.price) }}</strong><del>{{ language.price(product.originalPrice) }}</del><span>{{ language.t('save') }} {{ language.price(product.originalPrice-product.price) }}</span></div><p class="detail-description">{{ description }}</p><p class="stock">● {{ language.t('stock') }} {{ product.stock }} {{ language.t('items') }}</p><div class="purchase-row"><div class="quantity-control"><button @click="quantity=Math.max(1,quantity-1)">−</button><span>{{ quantity }}</span><button @click="quantity=Math.min(product.stock,quantity+1)">+</button></div><button class="button primary" @click="add">{{ added ? language.t('added') : language.t('addCart') }}</button><FavoriteButton :product-id="product.id" /></div><p class="shipping-note">✦ {{ language.t('freeShipping') }}</p></div></div><section class="detail-tabs"><div class="tab-list"><button v-for="tab in ['description','specifications','shipping','reviews']" :key="tab" :class="{active:activeTab===tab}" @click="activeTab=tab">{{ language.t(tab) }}</button></div><div class="tab-content"><p v-if="activeTab==='description'">{{ description }}</p><p v-else-if="activeTab==='specifications'">{{ language.t('detailSpecs') }}</p><p v-else-if="activeTab==='shipping'">{{ language.t('detailShipping') }}</p><p v-else>{{ language.t('detailReview') }}</p></div></section><section class="section related-section"><div class="section-heading"><h2>{{ language.t('related') }}</h2></div><ProductGrid :products="related" /></section></section><section v-else class="container page"><EmptyState :title="language.t('productNotFound')" :action="language.t('backHome')" /></section></template>
